#!/usr/bin/env node
/**
 * gen-tokens.mjs - Regenerates design token outputs from design-tokens/tokens.json.
 *
 * Inputs:
 *   design-tokens/tokens.json
 *
 * Outputs:
 *   web/src/styles/tokens.css      - CSS custom properties consumed by web
 *   crates/desktop/src/theme/generated.rs - Rust constants for GPUI
 *                                            (only written if the path exists)
 *
 * Both outputs are committed so downstream builds don't need this script.
 * Run with: node scripts/gen-tokens.mjs  (or: pnpm --dir web tokens)
 */

import { readFileSync, writeFileSync, existsSync, mkdirSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, "..");
const TOKENS_PATH = join(ROOT, "design-tokens/tokens.json");
const CSS_PATH = join(ROOT, "web/src/styles/tokens.css");
const RUST_PATH = join(ROOT, "crates/desktop/src/theme/generated.rs");

const HEADER_CSS = [
  "/* AUTO-GENERATED by scripts/gen-tokens.mjs. DO NOT EDIT BY HAND. */",
  "/* Edit design-tokens/tokens.json, then run: node scripts/gen-tokens.mjs */",
  "",
].join("\n");

const HEADER_RUST = [
  "// AUTO-GENERATED by scripts/gen-tokens.mjs. DO NOT EDIT BY HAND.",
  "// Edit design-tokens/tokens.json, then run: node scripts/gen-tokens.mjs",
  "#![allow(dead_code, clippy::unreadable_literal)]",
  "",
].join("\n");

// ---------- helpers ----------

/** Lower-kebab-case the path parts for CSS custom properties. */
const cssName = (path) => `--sx-${path.join("-")}`;

/** Upper-snake-case for Rust constants. */
const rustName = (path) => path.join("_").replace(/-/g, "_").toUpperCase();

/** Parse a hex color '#rrggbb' into { r, g, b } (0-255). */
const parseHex = (hex) => {
  const m = /^#?([0-9a-fA-F]{6})$/.exec(hex);
  if (!m) throw new Error(`bad hex: ${hex}`);
  const n = parseInt(m[1], 16);
  return { r: (n >> 16) & 0xff, g: (n >> 8) & 0xff, b: n & 0xff };
};

const toCssColor = ({ hex, alpha }) => {
  if (alpha === undefined || alpha === 1.0) return hex;
  const { r, g, b } = parseHex(hex);
  return `rgba(${r}, ${g}, ${b}, ${alpha})`;
};

/** Pack hex into u32 (0xRRGGBB). */
const toRustRgb = ({ hex }) => {
  const m = /^#?([0-9a-fA-F]{6})$/.exec(hex);
  if (!m) throw new Error(`bad hex: ${hex}`);
  return `0x${m[1].toUpperCase()}`;
};

// ---------- walkers ----------

/** Recurse tokens, calling emit(path[], value) on every leaf.
 *  A leaf is either: (a) a primitive (number/string), or
 *  (b) an object with a `hex` field (color token). */
function walk(obj, path, emit) {
  for (const [k, v] of Object.entries(obj)) {
    if (k.startsWith("_") || k.startsWith("$")) continue; // skip metadata
    const p = [...path, k];
    if (v !== null && typeof v === "object" && !Array.isArray(v) && !("hex" in v)) {
      walk(v, p, emit);
    } else {
      emit(p, v);
    }
  }
}

// ---------- main ----------

const tokens = JSON.parse(readFileSync(TOKENS_PATH, "utf8"));

// --- CSS ---
{
  const lines = [HEADER_CSS, ":root {"];
  walk(tokens, [], (path, v) => {
    const name = cssName(path);
    if (v !== null && typeof v === "object" && "hex" in v) {
      lines.push(`  ${name}: ${toCssColor(v)};`);
    } else if (typeof v === "number") {
      // Spacing/radius/font-size - emit as px. z-index, font.weight, motion.duration stay raw.
      const suffix =
        path[0] === "space" || path[0] === "radius" ||
        (path[0] === "font" && path[1] === "size")
          ? "px"
          : "";
      lines.push(`  ${name}: ${v}${suffix};`);
    } else if (typeof v === "string") {
      lines.push(`  ${name}: ${v};`);
    }
  });
  lines.push("}", "");
  mkdirSync(dirname(CSS_PATH), { recursive: true });
  writeFileSync(CSS_PATH, lines.join("\n"));
  console.log(`[tokens] wrote ${CSS_PATH}`);
}

// --- Rust (only if crates/desktop exists, which it won't until Phase 3) ---
if (existsSync(dirname(RUST_PATH))) {
  const lines = [HEADER_RUST];
  walk(tokens, [], (path, v) => {
    const name = rustName(path);
    if (v !== null && typeof v === "object" && "hex" in v) {
      const rgb = toRustRgb(v);
      if (v.alpha === undefined || v.alpha === 1.0) {
        lines.push(`pub const ${name}: u32 = ${rgb};`);
      } else {
        lines.push(`pub const ${name}_RGB: u32 = ${rgb};`);
        lines.push(`pub const ${name}_ALPHA: f32 = ${v.alpha};`);
      }
    } else if (typeof v === "number") {
      const ty = path[0] === "space" || path[0] === "radius" ||
                 (path[0] === "font" && path[1] === "size") ? "f32" : "u32";
      lines.push(`pub const ${name}: ${ty} = ${ty === "f32" ? `${v}.0` : v};`);
    } else if (typeof v === "string") {
      // Emit all strings (including CSS fragments like "cubic-bezier(...)").
      // Rust code doesn't have to use them; the `_unused_refs` sink in
      // theme/mod.rs keeps warnings quiet.
      lines.push(`pub const ${name}: &str = ${JSON.stringify(v)};`);
    }
  });
  lines.push("");
  mkdirSync(dirname(RUST_PATH), { recursive: true });
  writeFileSync(RUST_PATH, lines.join("\n"));
  console.log(`[tokens] wrote ${RUST_PATH}`);
} else {
  console.log(`[tokens] skipped Rust output (crates/desktop not present yet)`);
}
